name: learning_V2
channels:
  - anaconda
  - defaults
dependencies:
  - _tflow_select=2.2.0
  - absl-py=0.9.0
  - astor=0.8.1
  - blas=1.0
  - blinker=1.4
  - brotlipy=0.7.0
  - ca-certificates=2020.7.22
  - cachetools=4.1.1
  - certifi=2020.6.20
  - cffi=1.14.2
  - chardet=3.0.4
  - click=7.1.2
  - cloudpickle=1.6.0
  - cryptography=3.1
  - cycler=0.10.0
  - cytoolz=0.10.1
  - dask-core=2.25.0
  - decorator=4.4.2
  - freetype=2.10.2
  - gast=0.2.2
  - google-auth=1.21.1
  - google-auth-oauthlib=0.4.1
  - google-pasta=0.2.0
  - grpcio=1.31.0
  - h5py=2.8.0
  - hdf5=1.8.18
  - icc_rt=2019.0.0
  - icu=58.2
  - idna=2.10
  - imageio=2.9.0
  - importlib-metadata=1.7.0
  - intel-openmp=2020.2
  - jpeg=9b
  - keras=2.3.1
  - keras-applications=1.0.8
  - keras-base=2.3.1
  - keras-preprocessing=1.1.0
  - kiwisolver=1.2.0
  - libpng=1.6.37
  - libprotobuf=3.13.0
  - libtiff=4.1.0
  - lz4-c=1.9.2
  - markdown=3.2.2
  - matplotlib=3.3.1
  - matplotlib-base=3.3.1
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.0
  - networkx=2.5
  - numpy=1.19.1
  - numpy-base=1.19.1
  - oauthlib=3.1.0
  - olefile=0.46
  - openssl=1.1.1g
  - opt_einsum=3.1.0
  - pandas=1.1.1
  - pillow=7.2.0
  - pip=20.2.2
  - protobuf=3.13.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pyjwt=1.7.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pysocks=1.7.1
  - python=3.7.9
  - python-dateutil=2.8.1
  - pytz=2020.1
  - pywavelets=1.1.1
  - pyyaml=5.3.1
  - qt=5.9.7
  - requests=2.24.0
  - requests-oauthlib=1.3.0
  - rsa=4.6
  - scikit-image=0.16.2
  - scipy=1.5.2
  - setuptools=49.6.0
  - sip=4.19.24
  - six=1.15.0
  - sqlite=3.33.0
  - tensorboard=2.2.1
  - tensorboard-plugin-wit=1.6.0
  - tensorflow=2.1.0
  - tensorflow-base=2.1.0
  - tensorflow-estimator=2.1.0
  - termcolor=1.1.0
  - tk=8.6.10
  - toolz=0.10.0
  - tornado=6.0.4
  - urllib3=1.25.10
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - werkzeug=0.16.1
  - wheel=0.35.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - wrapt=1.12.1
  - xz=5.2.5
  - yaml=0.1.7
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.4
